require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('kaya_bot', '0.1.0') do |p|
  p.description    = "Interface to run Go Bots on Kaya"
  p.url            = "http://github.com/conanbatt/OpenKaya"
  p.author         = "Gabriel Benmergui"
  p.email          = "gabriel.benmergui@kaya.gs"
  p.ignore_pattern = ["tmp/*", "script/*"]
 # p.executable_pattern = ["bin/*"]
  p.development_dependencies = []
end

=begin
require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'
spec = Gem::Specification.new do |s|
  s.name = 'KayaBot'
  s.version = '0.1.0'
  s.has_rdoc = false
  s.extra_rdoc_files = ['README']
  s.summary = 'Interface to run Go Bots on Kaya'
  s.description = s.summary
  s.author = 'Gabriel Benmergui'
  s.email = 'gabriel.benmergui@kaya.gs'
  s.executables = %w('kaya_bot')
  s.files = %w(LICENSE README Rakefile) + Dir.glob("{bin,lib,spec}/**/*")
  s.require_path = "lib"
  s.bindir = "bin"
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

Rake::RDocTask.new do |rdoc|
  files =['README', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README" # page to start on
  rdoc.title = "Learning Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options 

=end
