var JGO_CLEAR=0,JGO_BLACK=1,JGO_WHITE=2,JGO_DEAD_BLACK=3,JGO_DEAD_WHITE=4,JGO_FILL=5,jgo_classes=["jgo_c","jgo_b","jgo_w","jgo_d jgo_b","jgo_d jgo_w","jgo_f"],jgo_shadow=[false,true,true,false,false,false],jgo_markers={_:["black","white"],"#":["square_b","square_w"],"*":["cross_b","cross_w"],"/":["triangle_b","triangle_w"],"0":["circle_b","circle_w"],"<":["hover_b","hover_b"],">":["hover_w","hover_w"],".":"territory_b",",":"territory_w"},jgo_coord="ABCDEFGHJKLMNOPQRST".split(""),jgo_sgf="abcdefghijklmnopqrstuvwxyz".split(""),
jgo_errorStr=false;function jgo_error(){return jgo_errorStr}function JGOCoordinate(a,b){if(a!=undefined)if(b!=undefined){this.i=a;this.j=b}else{this.j=this.i=0;if(typeof a=="string")if(a.substr(0,1).toUpperCase()==a.substr(0,1)){this.i=$.inArray(a.substr(0,1),jgo_coord);this.j=19-parseInt(a.substr(1))}else{this.i=$.inArray(a.substr(0,1),jgo_sgf);this.j=$.inArray(a.substr(1),jgo_sgf)}}else this.j=this.i=0}JGOCoordinate.prototype.toString=function(){return jgo_coord[this.i]+(19-this.j)};
JGOCoordinate.prototype.sgf=function(){return jgo_sgf[this.i]+jgo_sgf[this.j]};JGOCoordinate.prototype.copy=function(){return new JGOCoordinate(this.i,this.j)};function JGOBoard(a,b){this.width=a;this.height=b!=undefined?b:this.width;this.board=[];for(var c=0;c<a;++c){for(var d=[],f=0;f<b;++f)d.push(JGO_CLEAR);this.board.push(d)}}JGOBoard.prototype.get=function(a){return this.board[a.i][a.j]};
JGOBoard.prototype.set=function(a,b){if(a instanceof JGOCoordinate)this.board[a.i][a.j]=b;else if(a instanceof Array)for(var c=0,d=a.length;c<d;++c)this.board[a[c].i][a[c].j]=b};
JGOBoard.prototype.getAdjacent=function(a,b){var c=[],d=a.i,f=a.j;d>0&&this.board[d-1][f]==b&&c.push(new JGOCoordinate(d-1,f));d+1<this.width&&this.board[d+1][f]==b&&c.push(new JGOCoordinate(d+1,f));f>0&&this.board[d][f-1]==b&&c.push(new JGOCoordinate(d,f-1));f+1<this.height&&this.board[d][f+1]==b&&c.push(new JGOCoordinate(d,f+1));return c};
JGOBoard.prototype.getGroup=function(a){var b=this.get(a),c={};a=[a.copy()];for(var d=[],f=this;a.length>0;){newQueue=[];$.each(a,function(e,g){if(!(g.toString()in c)){d.push(g);c[g.toString()]=g;newQueue=newQueue.concat(f.getAdjacent(g,b))}});a=newQueue}return d};JGOBoard.prototype.hasLiberties=function(a){for(var b=0,c=a.length;b<c;++b)if(this.getAdjacent(a[b],JGO_CLEAR).length>0)return true;return false};
JGOBoard.prototype.clear=function(){var a=new JGOCoordinate(0,0);for(a.i=0;a.i<this.width;a.i++)for(a.j=0;a.j<this.height;a.j++)this.set(a,JGO_CLEAR)};JGOBoard.prototype.getDiff=function(a){var b=new JGOCoordinate(0,0),c=[[],[],[]],d;for(b.i=0;b.i<19;b.i++)for(b.j=0;b.j<19;b.j++)if(this.get(b)!=(d=a.get(b)))c[d].push(b.copy());return c};JGOBoard.prototype.each=function(a){var b=new JGOCoordinate(0,0);for(b.j=0;b.j<19;b.j++)for(b.i=0;b.i<19;b.i++)a.call(this,b.copy())};
JGOBoard.prototype.setDiff=function(a){this.set(a[JGO_CLEAR],JGO_CLEAR);this.set(a[JGO_BLACK],JGO_BLACK);this.set(a[JGO_WHITE],JGO_WHITE)};JGOBoard.prototype.setBoard=function(a){var b=new JGOCoordinate(0,0);for(b.i=0;b.i<19;b.i++)for(b.j=0;b.j<19;b.j++){stone=a.board[b.i][b.j];this.board[b.i][b.j]!=stone&&this.set(b,stone)}};JGOBoard.prototype.copy=function(){var a=new JGOBoard(this.width,this.height);a.setBoard(this);return a};
JGOBoard.prototype.toString=function(){var a=new JGOCoordinate(0,0),b=[],c=[".","#","O"];for(a.j=0;a.j<19;a.j++){for(a.i=0;a.i<19;a.i++)b.push(c[this.board[a.i][a.j]]);b.push("\n")}return b.join("")};JGOBoard.prototype.fromString=function(a){var b=0,c=new JGOCoordinate(0,0),d={".":JGO_CLEAR,"#":JGO_BLACK,O:JGO_WHITE};a=a.replace(/\n/g,"");for(c.j=0;c.j<19;c.j++)for(c.i=0;c.i<19;c.i++,b++){var f=d[a.charAt(b)];this.get(c)!=f&&this.set(c,f)}};
JGOBoard.prototype.play=function(a,b){var c=b==JGO_BLACK?JGO_WHITE:JGO_BLACK,d=0,f=this;if(this.get(a)!=JGO_CLEAR)return-1;this.set(a,b);c=this.getAdjacent(a,c);$.each(c,function(e,g){if(f.get(g)!=JGO_CLEAR){var k=f.getGroup(g);if(!f.hasLiberties(k)){f.set(k,JGO_CLEAR);d+=k.length}}});if(d==0&&!this.hasLiberties(this.getGroup(a))){this.set(a,JGO_CLEAR);return-1}return d};
function jgo_renderDiv(a,b){a.push("<div ");if("className"in b){a.push('class="');a.push(b.className);a.push('" ')}if("id"in b){a.push('id="');a.push(b.id);a.push('" ')}a.push('style="left: ');a.push(b.left);a.push("px; top: ");a.push(b.top);a.push("px;");if("width"in b){a.push(" width: ");a.push(b.width);a.push("px;")}if("height"in b){a.push(" height: ");a.push(b.height);a.push("px;")}if("position"in b){a.push(" background-position: ");a.push(b.position);a.push(";")}a.push('">');"content"in b&&a.push(b.content);
a.push("</div>")}var jgo_setups={normal:{classPrefix:"",topLeft:[28,28],bottomRight:[619,657],squareSize:[31,33],aaPosition:[45,47],stoneSize:[30,30],shadowSize:[57,50],stoneOffset:[13,5],coordSize:[24,24]},small:{classPrefix:"_s",topLeft:[19,19],bottomRight:[418,437],squareSize:[21,22],aaPosition:[30,31],stoneSize:[20,20],shadowSize:[38,33],stoneOffset:[8,3],coordSize:[16,16]}};
function jgo_generateBoard(a,b,c){var d=[],f,e;e=c?jgo_setups[c]:jgo_setups.normal;var g=new JGOBoard(19,19),k=g.set;g.markers={};g.click=undefined;g.setup=e;b||(b="");g.shadowPrefix="jgo_sh"+b;g.stonePrefix="jgo_st"+b;g.markerPrefix="jgo_m"+b;c=e.aaPosition[0]-e.coordSize[0]/2;f=e.topLeft[1]-e.coordSize[1];var h=e.bottomRight[1]+1,t=e.topLeft[0]-e.coordSize[0],n=e.aaPosition[1]-e.coordSize[1]/2,p=e.bottomRight[0]+1,q;for(b=0;b<19;b++){var o="jgo_coord"+e.classPrefix;q=""+(19-b);jgo_renderDiv(d,{left:c,
top:f,className:o,content:jgo_coord[b]});jgo_renderDiv(d,{left:c,top:h,className:o,content:jgo_coord[b]});jgo_renderDiv(d,{left:t,top:n,className:o,content:q});jgo_renderDiv(d,{left:p,top:n,className:o,content:q});c+=e.squareSize[0];n+=e.squareSize[1]}h=e.aaPosition[0]-e.stoneSize[0]/2;n=e.aaPosition[1]-e.stoneSize[1]/2;p=h-e.stoneOffset[0];o=n-e.stoneOffset[1];var u=e.bottomRight[0]+1-p-e.squareSize[0]*18,w=e.bottomRight[1]+1-o-e.squareSize[1]*18,x=0;if(u>e.shadowSize[0])u=0;if(w>e.shadowSize[1])w=
0;if(p<e.topLeft[0])x=e.topLeft[0]-p;for(f=0;f<19;f++){t=h;q=p;for(b=0;b<19;b++){c=jgo_sgf[b]+jgo_sgf[f];var r={left:q,top:o,className:"jgo_sh"+e.classPrefix,id:g.shadowPrefix+c};if(b==18&&u)r.width=u;if(f==18&&w)r.height=w;if(b==0&&x){r.left+=x;r.width=e.shadowSize[0]-x;r.position="top right"}jgo_renderDiv(d,r);jgo_renderDiv(d,{left:t,top:n,className:"jgo_c"+e.classPrefix,id:g.stonePrefix+c});jgo_renderDiv(d,{left:t,top:n,className:"jgo_m"+e.classPrefix,id:g.markerPrefix+c});t+=e.squareSize[0];q+=
e.squareSize[0]}n+=e.squareSize[1];o+=e.squareSize[1]}a.html(d.join(""));var y=function(i,j,l){var m=true;if(l=="")$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix);else if(l!=undefined){var s=jgo_markers[l];if(s==undefined){j==JGO_BLACK?$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix).addClass(jgo_markers._[1]).html(l):$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix).addClass(jgo_markers._[0]).html(l);if(j==JGO_CLEAR)j=JGO_FILL;
m=false}else if(l=="."||l==","){$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix).addClass(s);if(j==JGO_BLACK)j=JGO_DEAD_BLACK;else if(j==JGO_WHITE)j=JGO_DEAD_WHITE}else j==JGO_BLACK?$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix).addClass(s[1]):$("#"+this.markerPrefix+i).removeClass().addClass("jgo_m"+e.classPrefix).addClass(s[0])}m&&$("#"+this.markerPrefix+i).html("");$("#"+this.stonePrefix+i).removeClass().addClass(jgo_classes[j]+e.classPrefix);jgo_shadow[j]?
$("#"+this.shadowPrefix+i).show():$("#"+this.shadowPrefix+i).hide()};g.set=function(i,j){k.call(this,i,j);if(i instanceof Array){var l=this;$.each(i,function(s,z){var A=z.sgf();y.call(l,A,j,l.markers[A])})}else{var m=i.sgf();y.call(this,m,j,this.markers[m])}};g.mark=function(i,j){if(i instanceof Array){var l=this;$.each(i,function(s,z){l.mark(z,j)})}else{var m=i.sgf();if(j=="")delete this.markers[m];else this.markers[m]=j;y.call(this,m,this.get(i),j)}};g.clearMarkers=function(){var i=this;$.each(this.markers,
function(j){i.mark(new JGOCoordinate(j),"")})};a.find(".jgo_m").click(function(i){if(g.click!=undefined){i=i.target.id.substring(g.markerPrefix.length);g.click(new JGOCoordinate(i))}});return g};function JGONavigator(a){this.root=a;this.reset()}JGONavigator.prototype.next=function(a){if(a==undefined)a=0;if(this.seqPos+1<this.curTree.sequence.length){this.seqPos++;this.position++;return true}else if(this.curTree.leaves.length==0)return false;else{this.treeStack.push(this.curTree);this.branches.push(a);this.curTree=this.curTree.leaves[a];this.seqPos=0;this.position++;return true}};
JGONavigator.prototype.previous=function(){if(this.seqPos-1>=0){this.seqPos--;this.position--;return true}else if(this.treeStack.length==0)return false;else{this.curTree=this.treeStack.pop();this.branches.pop();this.seqPos=this.curTree.sequence.length-1;this.position--;return true}};JGONavigator.prototype.reset=function(){this.curTree=this.root;this.seqPos=0;this.treeStack=[];this.branches=[];this.position=0};JGONavigator.prototype.get=function(){return this.curTree.sequence[this.seqPos]};
JGONavigator.prototype.getPosition=function(){return this.position};JGONavigator.prototype.getVariations=function(){if(this.seqPos!=0||this.treeStack.length==0)return 0;return this.treeStack[this.treeStack.length-1].leaves.length-1};JGONavigator.prototype.getVariation=function(){if(this.branches.length==0)return 0;return this.branches[this.branches.length-1]};JGONavigator.prototype.isAtEnd=function(){return this.seqPos+1==this.curTree.sequence.length&&this.curTree.leaves.length==0};
JGONavigator.prototype.isAtBeginning=function(){return this.seqPos==0&&this.treeStack.length==0};function JGOPlayer(a){this.navigator=new JGONavigator(a);var b=this.navigator.get();var c=a=19;if("SZ"in b){b=b.SZ[0];if(b.indexOf(":")!=-1){a=parseInt(b.substring(0,b.indexOf(":")));c=parseInt(b.substr(b.indexOf(":")+1))}else a=c=parseInt(b)}this.board=new JGOBoard(a,c);this.info={};this.captures=[0,0];this.boardHistory=[];this.stateHistory=[];this.execute()}
var jgo_sgfProperties={C:jgo_sgfComment,B:jgo_sgfMove,W:jgo_sgfMove,TW:jgo_sgfMarker,TB:jgo_sgfMarker,CR:jgo_sgfMarker,TR:jgo_sgfMarker,MA:jgo_sgfMarker,SQ:jgo_sgfMarker,LB:jgo_sgfLabel,AB:jgo_sgfSetup,AW:jgo_sgfSetup,AE:jgo_sgfSetup,AN:jgo_sgfInfo,CP:jgo_sgfInfo,DT:jgo_sgfInfo,EV:jgo_sgfInfo,GN:jgo_sgfInfo,OT:jgo_sgfInfo,RO:jgo_sgfInfo,RE:jgo_sgfInfo,RU:jgo_sgfInfo,SO:jgo_sgfInfo,TM:jgo_sgfInfo,PC:jgo_sgfInfo,PB:jgo_sgfInfo,PW:jgo_sgfInfo,BR:jgo_sgfInfo,WR:jgo_sgfInfo,BT:jgo_sgfInfo,WT:jgo_sgfInfo};
JGOPlayer.prototype.execute=function(a){var b=this;this.state={};$.each(this.navigator.get(),function(c,d){if(c in jgo_sgfProperties&&(!a||c in a))jgo_sgfProperties[c].call(b,c,d)})};JGOPlayer.prototype.next=function(a){if(this.navigator.isAtEnd())return false;this.boardHistory.push(this.board.toString());this.stateHistory.push(this.state);this.navigator.next(a);this.execute();return true};
JGOPlayer.prototype.previous=function(){if(this.navigator.isAtBeginning())return false;this.board.fromString(this.boardHistory.pop());this.state=this.stateHistory.pop();this.navigator.previous();return true};JGOPlayer.prototype.reset=function(){if(this.navigator.isAtBeginning())return false;this.navigator.reset();this.board.fromString(this.boardHistory[0]);this.state=this.stateHistory[0];this.captures=[0,0];if(!("info"in this.state))this.info={};this.boardHistory=[];this.stateHistory=[];return true};
function jgo_sgfComment(a,b){this.state.comment=b[0]}function jgo_sgfMove(a,b){var c,d;d=a=="B"?JGO_BLACK:JGO_WHITE;this.state.move=d;if(b[0].length==2){c=new JGOCoordinate(b[0]);this.state.moveCoordinate=c;c=this.board.play(c,d);if(c==-1)this.state.error="SGF move contained suicide!";else{this.captures[d==JGO_BLACK?0:1]+=c;this.state.captures=c}}}
function jgo_sgfMarker(a,b){var c={TW:",",TB:".",CR:"0",TR:"/",MA:"*",SQ:"#"}[a];"markers"in this.state||(this.state.markers={});this.state.markers[c]=jgo_explodeSGFList(b)}function jgo_sgfLabel(a,b){var c;c="markers"in this.state?this.state.markers:this.state.markers={};$.each(b,function(d,f){var e=f.split(":");e[1]in c||(c[e[1]]=[]);c[e[1]].push(new JGOCoordinate(e[0]))})}
function jgo_sgfSetup(a,b){var c={AB:JGO_BLACK,AW:JGO_WHITE,AE:JGO_CLEAR};this.board.set(jgo_explodeSGFList(b),c[a]);this.state.setup=true}function jgo_sgfInfo(a,b){var c={AN:"annotator",CP:"copyright",DT:"date",EV:"event",GN:"gameName",OT:"overtime",RO:"round",RE:"result",RU:"rules",SO:"source",TM:"time",PC:"location",PB:"black",PW:"white",BR:"blackRank",WR:"whiteRank",BT:"blackTeam",WT:"whiteTeam"}[a];this.info[c]=b[0];"info"in this.state||(this.state.info={});this.state.info[c]=b[0]}
function jgo_explodeSGFList(a){var b=[];$.each(a,function(c,d){if(d.indexOf(":")==-1)b.push(new JGOCoordinate(d));else{var f=v.split(":"),e;e=new JGOCoordinate(f[0]);f=new JGOCoordinate(f[1]);coord=new JGOCoordinate;for(coord.i=e.i;coord.i<=f.i;++coord.i)for(coord.j=e.j;coord.j<=f.j;++coord.j)b.push(coord.copy())}});return b}
function jgo_parseSGF(a){var b,c,d,f=false,e=-1,g=[];if("a~b".split(/(~)/).length===3)b=a.split(/([\[\]\(\);])/);else{var k=0;b=[];c=0;for(d=a.length;c<d;++c)if("[]();".indexOf(a.charAt(c))!==-1){k<c&&b.push(a.substring(k,c));b.push(a.charAt(c));k=c+1}k<c&&b.push(a.substr(k,c))}c=0;for(d=b.length;c<d;++c){a=b[c];if(e==-1){a=jQuery.trim(a);if(a=="[")e=c;else a!=""&&g.push(a)}else if(a!="]")f=a.charAt(a.length-1)=="\\";else if(f)f=false;else{g.push(b.slice(e,c+1).join("").replace(/\\\]/g,"]"));e=-1}}if(g.length==
0){jgo_errorStr="SGF was empty!";return false}else if(g[0]!="("||g[1]!=";"||g[g.length-1]!=")"){jgo_errorStr='SGF did not start with "(;" or end with ")"!';return false}b=g;g=[];var h;f="";c=0;for(d=b.length;c<d;++c){a=b[c];if(a=="("||a==")"){if(h){if(f!=""&&h[f].length==0){jgo_errorStr="Missing property value at "+a+"!";return false}g.push(h);h=undefined}g.push(a)}else if(a==";"){if(f!=""&&h[f].length==0){jgo_errorStr="Missing property value at "+a+"!";return false}h&&g.push(h);h={};f=""}else if(a.indexOf("[")!=
0){if(f!=""&&h[f].length==0){jgo_errorStr="Missing property value at "+a+"!";return false}if(a in h){jgo_errorStr="Duplicate property identifier "+a+"!";return false}f=a;h[f]=[]}else{if(f==""){jgo_errorStr="Missing property identifier at "+a+"!";return false}h[f].push(a.substring(1,a.length-1))}}b=g;g=[];h={sequence:[],leaves:[]};c=1;for(d=b.length;c<d-1;++c){a=b[c];if(a=="("){if(h.sequence.length==0){jgo_errorStr="SGF contains a game tree without a sequence!";return false}g.push(h);h={sequence:[],
leaves:[]}}else if(a==")"){if(h.sequence.length==0){jgo_errorStr="SGF contains a game tree without a sequence!";return false}a=h;h=g.pop();h.leaves.push(a)}else h.sequence.push(a)}if(g.length>0){jgo_errorStr="Invalid number of parentheses in the SGF!";return null}return h};$(document).ready(function(){$(".jgo_auto").each(function(a,b){var c,d,f=$(b),e="jgo_auto"+a;if(f.hasClass("small")){f.html('<div class="@CLASS@" id="@UID@"></div><div class="jgo_controls"><div class="jgo_moves"><p class="jgo_mini"><a href="#" class="jgo_auto" id="first@UID@">&lt;&lt; first</a> <a href="#" class="jgo_auto" id="prev@UID@">&lt; prev</a> <span id="move@UID@">0</span> <a href="#" class="jgo_auto" id="next@UID@">next &gt;</a> <a href="#" class="jgo_auto" id="last@UID@">last &gt;&gt;</a></p></div><div class="jgo_variations"><p class="jgo_mini"><a href="#" class="jgo_auto" id="up@UID@">var. up</a> <span id="variation@UID@">1/1</span> <a href="#" class="jgo_auto" id="down@UID@">var. down</a></p></div><div class="jgo_captures"><p class="jgo_mini"><strong>B</strong> captures: <span id="black@UID@">0</span>, <strong>W</strong> captures: <span id="white@UID@">0</span></p></div><div style="clear: both;"></div></div>'.replace(/@UID@/g,
e).replace("@CLASS@","jgo_board small"));c=jgo_generateBoard($("#"+e),"a"+a,"small")}else{f.html('<div class="@CLASS@" id="@UID@"></div><div class="jgo_controls"><div class="jgo_moves"><p class="jgo_mini"><a href="#" class="jgo_auto" id="first@UID@">&lt;&lt; first</a> <a href="#" class="jgo_auto" id="prev@UID@">&lt; prev</a> <span id="move@UID@">0</span> <a href="#" class="jgo_auto" id="next@UID@">next &gt;</a> <a href="#" class="jgo_auto" id="last@UID@">last &gt;&gt;</a></p></div><div class="jgo_variations"><p class="jgo_mini"><a href="#" class="jgo_auto" id="up@UID@">var. up</a> <span id="variation@UID@">1/1</span> <a href="#" class="jgo_auto" id="down@UID@">var. down</a></p></div><div class="jgo_captures"><p class="jgo_mini"><strong>B</strong> captures: <span id="black@UID@">0</span>, <strong>W</strong> captures: <span id="white@UID@">0</span></p></div><div style="clear: both;"></div></div>'.replace(/@UID@/g,
e).replace("@CLASS@","jgo_board"));c=jgo_generateBoard($("#"+e),"a"+a)}if(f.attr("sgf")){var g=0;if(f.attr("move"))g=parseInt(f.attr("move"));jgo_autoLoadSGF(f.attr("sgf"),function(k){d=new JGOPlayer(k);if(g)for(;d.navigator.getPosition()<g;)if(!d.next())break;jgo_autoUpdater(c,d,e)})}$("#first"+e).click(function(){if(d){d.reset()&&jgo_autoUpdater(c,d,e);return false}});$("#next"+e).click(function(){if(d){d.next()&&jgo_autoUpdater(c,d,e);return false}});$("#prev"+e).click(function(){if(d){d.previous()&&
jgo_autoUpdater(c,d,e);return false}});$("#last"+e).click(function(){if(d){for(;d.next(););jgo_autoUpdater(c,d,e);return false}});$("#up"+e).click(function(){if(d){var k=d.navigator.getVariation();if(k!=0){d.previous();d.next(k-1);jgo_autoUpdater(c,d,e);return false}}});$("#down"+e).click(function(){if(d){var k=d.navigator.getVariation();if(!(k>=d.navigator.getVariations())){d.previous();d.next(k+1);jgo_autoUpdater(c,d,e);return false}}})})});
function jgo_autoUpdater(a,b,c){a.clearMarkers();a.setBoard(b.board);"markers"in b.state&&$.each(b.state.markers,function(f,e){a.mark(e,f)});if("moveCoordinate"in b.state){var d=b.state.moveCoordinate;a.markers[d.sgf()]||a.mark(d,"0")}$("#move"+c).html(b.navigator.getPosition());$("#black"+c).html(b.captures[0]);$("#white"+c).html(b.captures[1]);d=b.navigator.getVariations();if(b.navigator.getVariations()>0){$("#variation"+c).html(b.navigator.getVariation()+1+"/"+(d+1)).removeClass("disabled");$("#up"+
c).removeClass("disabled");$("#down"+c).removeClass("disabled")}else{$("#variation"+c).html("1/1").addClass("disabled");$("#up"+c).addClass("disabled");$("#down"+c).addClass("disabled")}if(b.navigator.isAtBeginning()){$("#first"+c).addClass("disabled");$("#prev"+c).addClass("disabled")}else{$("#first"+c).removeClass("disabled");$("#prev"+c).removeClass("disabled")}if(b.navigator.isAtEnd()){$("#next"+c).addClass("disabled");$("#last"+c).addClass("disabled")}else{$("#next"+c).removeClass("disabled");
$("#last"+c).removeClass("disabled")}}function jgo_autoLoadSGF(a,b){if(a.indexOf("http:")==0){a=encodeURIComponent(a);$.ajax({type:"GET",url:"http://jgosgf.appspot.com/?url="+a,dataType:"jsonp",success:function(c){c.error?alert(c.error):b(c)}})}else $.ajax({url:a,type:"GET",success:function(c){(c=jgo_parseSGF(c))?b(c):alert(jgo_error())},error:function(){alert("Could not find the SGF file in "+a)}});return false};
